### ISSUE TITLE
Loading api.ebay.com in development mode of rails

### ISSUE THREAD

**Issue by CR1AT0RS** [kayoom/ebay_client#12]
Hi,

Sorry but is there a suggested way to override the development mode to load api.ebay.com URL instead of sandbox.ebay.com ?

I tried to create a new module but it did not work. Apparently SOAP requests are breaking. I can rebundle the gem by changing the defaults.yml file but I don't think that's the right approach. 

```
development: &development
  <<: *defaults
  url: 'https://api.ebay.com/wsapi'
  warning_level: High
  savon_log_level: :debug

```

**Comment by bvogel** [comment]
you should create a config file `ebay_client.yml` and set the url in development to point to production.
