### ISSUE TITLE
Rails 4 upgrade

### ISSUE THREAD

**Issue by rushingfitness** [kayoom/ebay_client#5]
One thing if you want to upgrade to rails 4 with this gem. Change the api.rb file from 
"ActiveSupport::BasicObject" => "ActiveSupport::ProxyObject"

BasicObject is depricated

**Comment by gioch** [comment]
I have the same issue.

**Comment by bvogel** [comment]
Hi, I merged https://github.com/kayoom/ebay_client/pull/6 - this should fix it. Until @cice releases a new gem you can use `gem 'ebay_client', github: 'kayoom/ebay_client'`

**Comment by cice** [comment]
under what version should i release? are there breaking changes?

**Comment by bvogel** [comment]
Hi @cice - any version below 1.0 is considered a "development" release if you follow the semver directive (http://semver.org/#spec-item-4) so 0.2.0 should be fine.

**Comment by cice** [comment]
https://rubygems.org/gems/ebay_client/versions/0.2.0 pushed.
