### ISSUE TITLE
Proper Documentation

### ISSUE THREAD

**Issue by gioch** [kayoom/ebay_client#8]
I'm using eBay API for the first time and have no clue how to make calls. Please add some normal documentation, with examples like how to add fixed price item, how to create item type and so on. It will be very helpful. Right now i have a gem that i know does some stuff, but have no idea how to force it to do that stuff. Its very distracting and pissing me off. Please add some proper examples.

**Comment by bvogel** [comment]
Hi @gioch, sorry to hear that you have difficulties using the gem. To get started please refer to the API documentation over at ebay. All you have to do is to feed a well formatted Hash to the snakecased method name:
```
api.add_dispute({ "OrderLineItemID" => order_line_item_id, "DisputeExplanation" => "BuyerReturnedItemForRefund", "DisputeReason" => "TransactionMutuallyCanceled" })
```
HTH

**Comment by cexposito** [comment]
Documentation is not the best, a few examples is all that is needed

Is the following correct format for getOrders passing an Array of OrderIDs?

get_orders("eBayAuthToken" => "aasdwdd112", "OrderIDArray" => [ {"OrderID" => "1"}, {"OrderID" => "2"},]

**Comment by bvogel** [comment]
@cexposito: No, the authentication goes into the `ebay_client.yml`. Apart from that the second part is correct...

**Comment by cexposito** [comment]
For scenarios where you have permissions to access other ebay stores, it is valid to include the eBayAuthToken field in the request

**Comment by bvogel** [comment]
Hi @cexposito, I rechecked the [documentation](http://developer.ebay.com/devzone/xml/docs/reference/ebay/getorders.html#Input) and I can't find any mentioning of the eBayAuthToken in the request body. It belongs into the request header:
```(xml)
   <soapenv:Header>
      <urn:RequesterCredentials>
         <urn:eBayAuthToken>?</urn:eBayAuthToken>
         <urn:HardExpirationWarning>?</urn:HardExpirationWarning>
         <urn:Credentials>
            <urn:AppId>?</urn:AppId>
            <urn:DevId>?</urn:DevId>
            <urn:AuthCert>?</urn:AuthCert>
            <urn:Username>?</urn:Username>
            <urn:Password>?</urn:Password>
         </urn:Credentials>
         <urn:NotificationSignature>?</urn:NotificationSignature>
      </urn:RequesterCredentials>
   </soapenv:Header>
```
Currently there is no way I'd know of to support adding a header field to a call.

**Comment by cexposito** [comment]
Take a look the xml message for getOrders, there is an eBayAuthToken

```
<?xml version="1.0" encoding="utf-8"?>
<GetOrdersRequest xmlns="urn:ebay:apis:eBLBaseComponents">
  <RequesterCredentials>
    **<eBayAuthToken>ABC...123</eBayAuthToken>**
  </RequesterCredentials>
  <CreateTimeFrom>2007-12-01T20:34:44.000Z</CreateTimeFrom>
  <CreateTimeTo>2007-12-10T20:34:44.000Z</CreateTimeTo>
  <OrderRole>Seller</OrderRole>
  <OrderStatus>Active</OrderStatus>
</GetOrdersRequest>
```
