### ISSUE TITLE
Allow to add attributes to tags

### ISSUE THREAD

**Issue by GCorbel** [kayoom/ebay_client#9]
As you can see in [the doc](http://developer.ebay.com/devzone/XML/docs/Reference/eBay/AddOrder.html#AddOrder) some tag needs attributes. For example, `<Total currencyID="CurrencyCodeType"> AmountType (double) </Total>`.

When I do this : 

`EbayClient.api.add_order({ order: { creating_user_role: 'Buyer', total: 123 } })`

I have this result : 

```
#<EbayClient::Response:0x0000000c25b370
 @ack="Failure",
 @build="E949_CORE_API_17895653_R1",
 @correlation_id=nil,
 @errors=
  [#<EbayClient::Response::Error:0x0000000c25b2f8
    @classification="RequestError",
    @code="10009",
    @long_message="No <Order.Total.CurrencyID> exists or <Order.Total.CurrencyID> is specified as an empty tag in the request.",
    @parameters={"0"=>"Order.Total.CurrencyID"},
    @severity_code="Error",
    @short_message="No <Order.Total.CurrencyID> exists or <Order.Total.CurrencyID> is specified as an empty tag.">,
   #<EbayClient::Response::Error:0x0000000c25b230
    @classification="RequestError",
    @code="10009",
    @long_message="No <Order.TransactionArray> exists or <Order.TransactionArray> is specified as an empty tag in the request.",
    @parameters={"0"=>"Order.TransactionArray"},
    @severity_code="Error",
    @short_message="No <Order.TransactionArray> exists or <Order.TransactionArray> is specified as an empty tag.">],
 @payload={:timestamp=>Mon, 04 Apr 2016 19:27:27 +0000},
 @timestamp=Mon, 04 Apr 2016 19:27:27 +0000,
 @version="949">
```

I have no clue by reading the doc. Is there a solution or is it not implemented yet.

Thanks!

**Comment by bvogel** [comment]
Hi,

you really need to read and understand the documentation of the ebay TradingAPI. Here you are clearly advised to add a TransactionArray to your order element. WRT the attribute 5 seconds of googling brought me this: http://stackoverflow.com/questions/16527963/savon-2-1-adding-attributes-to-message-xml-tags (as ebay_client uses savon to handle the ebay soap request)

B.

P.D. Please don't take this the wrong way. I would love to have a decent documentation for this gem but I just did a bit of maintenance to it to keep it afloat as we use it and I'm on a very limit time budget to maintain this properly.

**Comment by GCorbel** [comment]
You're right. I read the doc and it's not obvious but it works. Thanks.
